name: TestDeploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:

    # using Ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./TestApplication

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1 #this installs node and npm for us
      with:
        node-version: '10.x'

    - uses: actions/cache@v1 # this allows for re-using node_modules caching, making builds a bit faster.
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: npm install
    - run: npm install -g @angular/cli > /dev/null
    - run: ng build --prod



    - name: copy file to folder
      uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
      with:
       dir: dist
       branch: AngulrApp
       token: ${{ secrets.forSSH }}
